[package]
name = "delta_inc"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An API capturing delta transformations and incremental computations"
repository = "https://github.com/DavePearce/DeltaInc.rs"

[dependencies]
